language: python
python:
  - "3.6"

install:
  - pip install -U pyinstaller
  - pip install -U -r requirements.txt

jobs:
  include:
    - stage: Build binary and deploy to github on new releases
      script: pyinstaller --onefile -n supervisor --hidden-import=boto3 --hidden-import=urllib3 faassupervisor/supervisor.py
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: dist/supervisor
          skip_cleanup: true
          on:
            tags: true
      if: tag IS present
    - stage: Deploy to PyPi on new releases
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USER
          password: $PYPI_PASS
          on:
            tags: true
      if: tag IS present
