dist: xenial
language: python
python:
  - "3.7.1"

install:
  - pip3 install -U pyinstaller
  - pip3 install -U -r requirements.txt

jobs:
  include:
    - stage: Build binary and deploy to github on new releases
      script: >
        pyinstaller --onefile -n supervisor faassupervisor/supervisor.py
        --hidden-import faassupervisor.providers.aws.lambda_.supervisor
        --hidden-import faassupervisor.providers.aws.batch.supervisor
        --hidden-import faassupervisor.providers.onpremises.openfaas.supervisor
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: dist/supervisor
          skip_cleanup: true
          on:
            tags: true
      if: tag IS present
    - stage: Deploy to PyPi on new releases
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USER
          password: $PYPI_PASS
          on:
            tags: true
      if: tag IS present
