dist: xenial
language: python
python:
  - "3.7.1"

install:
  - pip3 install -U pyinstaller
  - pip3 install -U -r requirements.txt

jobs:
  include:
    - stage: Build binary and deploy to github on new releases
      script: >
        pyinstaller --onefile -n supervisor faassupervisor/supervisor.py
        --hidden-import faassupervisor.faas.openfaas.supervisor
        --hidden-import faassupervisor.faas.aws.lambda_.supervisor
        --hidden-import faassupervisor.faas.aws.batch.supervisor
        --hidden-import faassupervisor.events.apigateway
        --hidden-import faassupervisor.events.minio
        --hidden-import faassupervisor.events.onedata
        --hidden-import faassupervisor.events.s3
        --hidden-import faassupervisor.events.unknown
        --hidden-import faassupervisor.storage.providers.minio
        --hidden-import faassupervisor.storage.providers.onedata
        --hidden-import faassupervisor.storage.providers.s3
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: dist/supervisor
          skip_cleanup: true
          on:
            tags: true
      if: tag IS present
    - stage: Deploy to PyPi on new releases
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USER
          password: $PYPI_PASS
          on:
            tags: true
      if: tag IS present
