sudo: required
dist: xenial
language: python
python:
  - "3.7.1"

services:
  - docker

install:
  - pip3 install -U pyinstaller
  - pip3 install -U -r requirements.txt

jobs:
  include:
    - stage: Build binary and deploy to github on new releases
      script: pyinstaller --onefile -n supervisor faassupervisor/supervisor.py
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: dist/supervisor
          skip_cleanup: true
          on:
            tags: true
      if: tag IS present
    - stage: Deploy to PyPi on new releases
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USER
          password: $PYPI_PASS
          on:
            tags: true
      after_success:
        - docker login -u $DOCKER_CLOUD_USER -p $DOCKER_CLOUD_PASS
        - export REPO=grycap/scar-batch-io
        - docker build -t $REPO -f faassupervisor/faas/aws/batch/docker_image/Dockerfile faassupervisor/faas/aws/batch/docker_image/
        - docker tag $REPO $REPO:latest
        - docker tag $REPO $REPO:$TRAVIS_TAG
        - docker push $REPO
      if: tag IS present